### ISSUE TITLE
node selection

### ISSUE THREAD

**Issue by meredrica** [meredrica/helm#16]
a way to select a cluster node would be nice.
https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/

could work like this and support direct nodename as well as labeled nodes
```yaml
deployment:
 node: "host"
```
for a labeled node:
```yaml
deployment:
  node:
    label: value
```
