### ISSUE TITLE
node selection

### ISSUE THREAD

**Issue by meredrica** [meredrica/helm#17]
a way to select a cluster node would be nice.
https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/

could work like this and support direct nodename as well as labeled nodes
```yaml
deployment:
 node: "host"
```
for a labelled node:
```yaml
deployment:
  node:
    label: value
```

**Comment by meredrica** [comment]
scheduling to a specific node is easy
```yaml
spec:
  nodeName: foo-node # schedule pod to specific node
```
labelled nodes too
```yaml
spec:
  nodeSelector:
    disktype: ssd #this is the whole label
```

**Comment by meredrica** [comment]
as for affinity, this is a little more complicated
there are two ways to specify preferred or required

required:
```yaml
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
```

preferred:
```yaml
spec:
  affinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
  ```

match expressions are always the same format
```yaml
- key: another-node-label-key
  operator: In
  values:
  - another-node-label-value
```
operators are defined here: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#operators

Topology spread will not be done with this feature, I'll add a new one

**Comment by meredrica** [comment]
additionally, ` podAffinity` can be used instead of `nodeAffinity`

**Comment by meredrica** [comment]
so, one way would be for short syntax:

```yaml
deployment: 
  node: "name"
```

long syntax:
```yaml
deployment:
  node:
    'label' : "value"
```

affinity could be done like this:
```yaml
deployment:
  affinity:
    pod:
    node:
```
still thinking about how to do the rest and how to avoid the duplicate `node`
